server:
  port: 8082
spring:
  data:
    mongodb:
      database: matty
      host: localhost
      port: 27017
      username: mongoroot
      password: toorognom
      authentication-database: admin
app:
  verification-code:
    ttl: 300000
logging:
  level:
    app.matty.api: DEBUG